format = """
╭─$time\
$username\
$hostname\
$directory\
$git_branch$git_status\
$python\
$golang\
$kubernetes\
$cmd_duration\
$custom
╰─> $env_var
"""
palette = 'jbertozzi'

[python]
format = '[ $virtualenv]($style)'
disabled = true

[username]
style_user = 'fg:white'
style_root = 'fg:red'
format = '[$user@]($style)'
disabled = false

[hostname]
ssh_only = false
format='[$hostname]($style) '
style = 'fg:white'

[custom.lunch]
when = '(( ($(date +%s -d "11:30") - $( date +%s )) < 3600 ))'
command = 'echo $(( $(date +%s -d "11:30") - $( date +%s ) ))'
format = '$output seconds before lunch'
disabled = true

[env_var.VAULT_ADDR]
variable = 'VAULT_ADDR'
style = "fg:blue"
format = '([\($env_value\)]($style)) '
disabled = true

[kubernetes]
style = "fg:blue"
format = '[󱃾 $context:$namespace ]($style)'
disabled = false
detect_folders = [ 'vars' ]

[directory]
style = "fg:yellow"
format = "[$path ]($style)"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:orange"
format = '[$symbol $branch ]($style)'

[git_status]
style = "fg:orange"
format = '([\($all_status$ahead_behind\)]($style) )'
#format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%T"
style = "fg:grey"
format = '[ $time ]($style)'

[cmd_duration]
style="fg:white"
min_time=1_000
format = '\([$duration]($style)\) '

[palettes.jbertozzi]
blue = '#87afd7'
white = '#e4e4e4'
grey = '#585858'
orange = '#fca17d'
yellow = '#cccc00'
