require("config.mason")
require("config.lualine")
require("config.lsp")
require("diffview")
require("config.cmp")
require("config.luasnip")
require("config.telescope")
require("config.workspaces")
require("config.autopairs")
-- --require("config.vimwiki")
require('Comment').setup()
require("config.treesitter")
require("config.neoscroll")
require("config.gitsigns")
